// Auto-generated by scripts/generate-build.mjs
export const APP_VERSION = "1.1.1";
export const APP_BUILD = "415";
export const APP_COMMIT = "f7fe697";
export const APP_BUILT_AT = "2026-04-29T14:39:03.823Z";
export const APP_BUILD_LABEL = "v1.1.1 · build 415";
