// Auto-generated by scripts/generate-build.mjs
export const APP_VERSION = "1.1.0";
export const APP_BUILD = "402";
export const APP_COMMIT = "a743ecf";
export const APP_BUILT_AT = "2026-04-27T21:18:01.796Z";
export const APP_BUILD_LABEL = "v1.1.0 · build 402";
