import {
  FileText,
  BookOpen,
  CheckSquare,
  Target,
  Receipt,
  Car,
  Users,
  Wallet,
  Calendar,
} from "lucide-react";

export const ACTIVE_PLUGINS = [
  {
    id: "report",
    name: "Outil Rapport",
    label: "Outil Rapport",
    desc: "Rapports professionnels rapides",
    icon: FileText,
    iconName: "FileText",
    path: "/plugins/report",
    color: "38 50% 58%",
  },
  {
    id: "logbook",
    name: "Journal de bord",
    label: "Journal de bord",
    desc: "Entrées chronologiques",
    icon: BookOpen,
    iconName: "BookOpen",
    path: "/plugins/logbook",
    color: "217 91% 60%",
  },
  {
    id: "tasks",
    name: "Tâches",
    label: "Tâches",
    desc: "Gestionnaire de tâches simple",
    icon: CheckSquare,
    iconName: "CheckSquare",
    path: "/plugins/tasks",
    color: "142 71% 45%",
  },
  {
    id: "missions",
    name: "Gestionnaire de missions",
    label: "Gestionnaire de missions",
    desc: "Missions & affectations",
    icon: Target,
    iconName: "Target",
    path: "/plugins/missions",
    color: "0 72% 51%",
  },
  {
    id: "quotes",
    name: "Devis & Factures",
    label: "Devis & Factures",
    desc: "Facturation & paiements",
    icon: Receipt,
    iconName: "Receipt",
    path: "/plugins/quotes",
    color: "270 50% 60%",
  },
  {
    id: "vehicle",
    name: "Carnet de véhicule",
    label: "Carnet de véhicule",
    desc: "Kilométrage & suivi IK",
    icon: Car,
    iconName: "Car",
    path: "/plugins/vehicle",
    color: "38 92% 50%",
  },
];

export const LOCKED_PLUGINS = [
  {
    name: "CRM Lite",
    desc: "Gestion clients",
    icon: Users,
    eta: "Q3 2025",
  },
  {
    name: "Suivi budget",
    desc: "Vue financière",
    icon: Wallet,
    eta: "Q4 2025",
  },
  {
    name: "Outil réservation",
    desc: "Prise de rendez-vous",
    icon: Calendar,
    eta: "2026",
  },
];
