import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const outFile = resolve(root, "src/config/build.ts");

function run(command, fallback = "") {
  try {
    return execSync(command, { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return fallback;
  }
}

const commit = process.env.VERCEL_GIT_COMMIT_SHA || run("git rev-parse HEAD", "local");
const shortCommit = commit.slice(0, 7);
const count = process.env.VERCEL_GIT_COMMIT_REF
  ? run("git rev-list --count HEAD", "0")
  : run("git rev-list --count HEAD", "0");
const buildNumber = Number(count) > 0 ? count : String(Date.now());
const builtAt = new Date().toISOString();
const version = packageJson.version || "1.1.0";

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// Auto-generated by scripts/generate-build.mjs\n` +
    `export const APP_VERSION = "${version}";\n` +
    `export const APP_BUILD = "${buildNumber}";\n` +
    `export const APP_COMMIT = "${shortCommit}";\n` +
    `export const APP_BUILT_AT = "${builtAt}";\n` +
    `export const APP_BUILD_LABEL = "v${version} · build ${buildNumber}";\n`,
  "utf8"
);

console.log(`Generated ${outFile}: v${version} build ${buildNumber} (${shortCommit})`);
